name: Docker CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - "9.0"
        ocaml_version:
          - "4.14-flambda"
      max-parallel: 4
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile under docker
        uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-ctree.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          export: 'OPAMWITHTEST'
          before_install: |
            startGroup "Workaround permission issue"
              sudo chown -R 1000:1000 .
            endGroup
            startGroup "Generate Opam File"
              dune build rocq-ctree.opam
            endGroup
            startGroup "Print opam config"
              opam config list; opam repo list; opam list
            endGroup
        env:
          OPAMWITHTEST: 'true'

